@echo off
echo Removing git lock...
del /f ".git\index.lock" 2>nul
echo Staging ParentApp.tsx...
git add src/pages/ParentApp.tsx
echo Committing...
git commit -m "fix: remove duplicate Toggle and orphaned JSX, add AlertCircle import"
echo Pushing...
git push origin master
echo Done! Check Vercel for the new build.
pause
